version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    image: nginx:alpine
    expose:
      - "8280"
    command: ["nginx", "-g", "daemon off;"]
